config/routes.rb
Rails.application.routes.draw do

  root to: "homes#show"

  resources :dashboards
  resources :shouts, only: [:create, :show]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]

  resources :users, only: [:create, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest
    def email
        ""
    end
end

app/models/photo_shout.rb
class PhotoShout < ApplicationRecord
  has_attached_file :image, styles: { thumb: "200x200" }

  validates_attachment :image,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
  size: { in: 0..10.megabytes },
  presence: true
end

app/models/shout.rb
class Shout < ApplicationRecord
  belongs_to :user
  belongs_to :content, polymorphic: true

  validates :user, presence: true

  default_scope { order(created_at: :desc)}

  delegate :username, to: :user
end

app/models/text_shout.rb
class TextShout < ApplicationRecord
    validates :body, presence: true, length: { in: 1..144 }
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :username, presence: true, uniqueness: true
  
  has_many :shouts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @shout = Shout.new
    @shouts = current_user.shouts
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    before_action :redirect_to_dashboard_if_signed_in

    def show
    end

    private

    def redirect_to_dashboard_if_signed_in
        if signed_in?
            redirect_to "/dashboards/show"
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

    private

    def authenticate(_)
        super(session_params)
    end

    def session_params
        { session: session_params_with_email }
    end

    def session_params_with_email
        params.
          require(:session).
          permit(:password).
          merge(email: user.email)
    end

    def user
        User.where(email: email_or_username).or(User.where(username: email_or_username)).first || Guest.new
    end

    def email_or_username
        params[:session][:email_or_username]
    end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController

    def show
        @shout = Shout.find(params[:id])
    end
    def create
        shout = current_user.shouts.create(shout_params)
        redirect_to root_path, redirect_options_for(shout)
    end

    private

    def shout_params
        { content: content_from_params }
    end

    def content_from_params
        case params[:shout][:content_type]
        when "TextShout" then TextShout.new(text_shout_content_params)
        when "PhotoShout" then PhotoShout.new(photo_shout_content_params)
        end
        
    end

    def text_shout_content_params
        params.require(:shout).require(:content).permit(:body)
    end

    def photo_shout_content_params
        params.require(:shout).require(:content).permit(:image)
    end

    def redirect_options_for(shout)
        if shout.persisted?
            { notice: "Shouted succesfully" }
        else
            { alert: "Could not Shout!"}
        end
    end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
        @shouts = @user.shouts
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :username )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shouts_helper.rb
module ShoutsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/show.html.erb
<h1>Dashboard</h1>

<%= form_for @shout do |form| %>
  <%= form.hidden_field :content_type, value: "TextShout" %>
  <%= form.fields_for :content do |content_form| %>
    <%= content_form.text_field :body, placeholder: "Shout here!", required: true %><br/>
  <% end %>
  <%= form.submit "Shout!" %>
<% end %>

<%= form_for @shout do |form| %>
  <%= form.hidden_field :content_type, value: "PhotoShout" %>
  <%= form.fields_for :content do |content_form| %>
    <%= content_form.file_field :image, required: true %><br/>
  <% end %>
  <%= form.submit "Shout!" %>
<% end %>
 
<%= render @shouts %>

app/views/homes/show.html.erb
<h1> Shoutr </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoutr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= link_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/photo_shouts/_photo_shout.html.erb
<%= image_tag(photo_shout.image(:thumb)) %>

app/views/shouts/_shout.html.erb
<div>
    <%= link_to shout.username, shout.user %>
    <%= render shout.content %>
    <%= link_to shout do %>
      <%= time_ago_in_words(shout.created_at) %> ago
    <% end %>
  </div>

app/views/shouts/show.html.erb
<%= render @shout %>

app/views/text_shouts/_text_shout.html.erb
<%= text_shout.body %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %><br/>
  <%= form.email_field :email, placeholder: 'Enter your user name here' %>
</div>

<div class="text-field">
  <%= form.label :username, 'User Name' %><br/>
  <%= form.text_field :username, placeholder: 'Enter your user mail here' %>
</div>

<div class="password-field">
  <%= form.label :password %><br/>
  <%= form.password_field :password, placeholder: 'Enter your password here' %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

 
 
<%= render @shouts %>